import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

export let translate = new LocalizedStrings({
  "en-US": {
  },
  en: {
        privacyHeader: "Privacy policy",
        privacyTeaser: "",
        privacyChangeLanguage: "",
        privacyTitle1: "Hi",
        privacyTitle2: "",
        privacyTitle3: "",
        privacyTitle4: "",
        privacyTitle5: "",
        privacyTitle6: "",
        privacyTitle7: "",
        privacyTitle8: "",
        privacyTitle9: "",
        privacyTitle10: "",
        privacyTitle11: "",
        privacyTitle12: "",
        privacyTitle13: "",
        privacyTitle14: "",
        privacyTitle15: "",
        privacyTitle16: "",
        privacyTitle17: "",
        privacyTitle18: "",
        privacyText1: "",
        privacyText2: "",
        privacyText3: "",
        privacyText4: "",
        privacyText5: "",
        privacyText6: "",
        privacyText7: "",
        privacyText8: "",
        privacyText9: "",
        privacyText10: "",
        privacyText11: "",
        privacyText12: "",
        privacyText13: "",
        privacyText14: "",
        privacyText15: "",
        privacyText16: "",
        privacyText17: "",
        privacyText18: "",
        legalChangeLanguage: "",
        legalTeaser: "",
        legalHeader: "",
        legalTitle1: "",
        legalTitle2: "",
        legalTitle3: "",
        legalTitle4: "",
        legalTitle5: "",
        legalTitle6: "",
        legalTitle7: "",
  },
  de: {
        privacyHeader: "Datenschutzerklärung",
        privacyTeaser: "Diese Datenschutz-Erklärung dient der Information darüber, welche Art von Daten auf dieser App erhoben, gespeichert und verarbeitet werden und wie der Schutz und die Sicherheit der personenbezogenen Daten gewährleistet werden.",
        privacyTitle1: "1. Grundsätzliche Information",
        privacyTitle2: "2. Personenbezogene Daten",
        privacyTitle3: "3. Rechtsgrundlage für die Erhebung Verarbeitung personenbezogener Daten",
        privacyTitle4: "4. Datenlöschung und Speicherdauer",
        privacyTitle5: "5. Erhebung und Verarbeitung personenbezogener Daten",
        privacyTitle6: "6. Kontakt",
        privacyTitle7: "7. Datenübermittlung an Dritte",
        privacyTitle8: "8. Google Analytics",
        privacyTitle9: "9. Soziale Netzwerke",
        privacyTitle10: "10. Datensicherheit",
        privacyTitle11: "11. Cookies und Tracking-Technologien",
        privacyTitle12: "12. Freiwillige Angaben",
        privacyTitle13: "13. Von Admob erhobene Daten ",
        privacyTitle14: "14. Datenschutzbeauftragte",
        privacyTitle15: "15. Kontaktdaten des Verantwortlichen:",
        privacyText1: "Soweit in den folgenden Abschnitten nicht anderweitig dargestellt, werden bei Nutzung unserer Webseiten grundsätzlich keine personenbezogenen Daten erhoben, verarbeitet oder genutzt. Wenn Sie auf unsere Internetseiten zugreifen, erfassen unsere Web-Server automatisch Informationen allgemeiner Natur. Dazu gehören die Art des Webbrowsers, das verwendete Betriebssystem, der Domainname des Internet Service Providers, die IP-Adresse des verwendeten Computers, die Webseite, von der aus Sie uns besuchen, die Seiten, die Sie bei uns besuchen sowie das Datum und die Dauer des Besuches. Diese Daten können von uns nicht dazu verwendet werden, den einzelnen Nutzer zu identifizieren. Die Informationen werden von uns lediglich statistisch ausgewertet und ausschließlich dazu verwendet, die Attraktivität, Inhalte und Funktionalitäten unserer Webseiten zu verbessern.",
        privacyText2: "In der EU-Datenschutz-Grundverordnung (DSGVO), sind personenbezogene Daten folgendermaßen definiert: Alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person (im Folgenden „betroffene Person“) beziehen; als identifizierbar wird eine natürliche Person angesehen, die direkt oder indirekt, insbesondere mittels Zuordnung zu einer Kennung wie einem Namen, zu einer Kennnummer, zu Standortdaten, zu einer Online-Kennung oder zu einem oder mehreren besonderen Merkmalen identifiziert werden kann, die Ausdruck der physischen, physiologischen, genetischen, psychischen, wirtschaftlichen, kulturellen oder sozialen Identität dieser natürlichen Person sind.",
        privacyText3: "Soweit wir für Verarbeitungsvorgänge personenbezogener Daten Ihre Einwilligung einholen, dient Art. 6 Abs. 1 lit. a DSGVO als Rechtsgrundlage für die Verarbeitung Ihrer personenbezogener Daten. Bei der Verarbeitung Ihrer personenbezogenen Daten zur Erfüllung eines Vertrages zwischen Ihnen und RICHLIST, dient Art. 6 Abs. 1 lit. b DSGVO als Rechtsgrundlage. Dies gilt auch für Verarbeitungsvorgänge, die zur Durchführung vorvertraglicher Maßnahmen erforderlich sind. Soweit eine Verarbeitung personenbezogener Daten zur Erfüllung einer rechtlichen Verpflichtung erforderlich ist, der unser Unternehmen unterliegt, dient Art. 6 Abs. 1 lit. c DSGVO als Rechtsgrundlage. Ist die Verarbeitung zur Wahrung eines berechtigten Interesses unseres Unternehmens oder eines Dritten erforderlich und überwiegen die Interessen, Grundrechte und Grundfreiheiten des Betroffenen das erstgenannte Interesse nicht, so dient Art. 6 Abs. 1 lit. f DSGVO als Rechtsgrundlage für die Verarbeitung.",
        privacyText4: "Die personenbezogenen Daten der betroffenen Person werden gelöscht oder gesperrt, sobald der Zweck der Speicherung entfällt. Eine Speicherung kann darüber hinaus dann erfolgen, wenn dies durch den europäischen oder nationalen Gesetzgeber in unionsrechtlichen Verordnungen, Gesetzen oder sonstigen Vorschriften, denen der Verantwortliche unterliegt, vorgesehen wurde. Eine Sperrung oder Löschung der Daten erfolgt auch dann, wenn eine durch die genannten Normen vorgeschriebene Speicherfrist abläuft, es sei denn, dass eine Erforderlichkeit zur weiteren Speicherung der Daten für einen Vertragsabschluss oder eine Vertragserfüllung besteht.",
        privacyText5: "ersonenbezogene Daten werden von uns nur erfasst, wenn Sie uns diese von sich aus mitteilen, beispielsweise wenn Sie sich bei uns registrieren oder mit uns in Kontakt treten. Wir verwenden die von Ihnen angegebenen personenbezogenen Daten ausschließlich, soweit Ihre Daten zur Erfüllung unserer Dienstleistungen notwendig sind. Eine darüber hinaus gehende Verwendung Ihrer Daten, beispielsweise zu weiteren Serviceleistungen oder Werbezwecken, findet nur statt, wenn Sie zuvor ausdrücklich dazu eingewilligt haben. Ihre Einwilligung können Sie jederzeit für die Zukunft widerrufen. Nach vollständiger Vertragsabwicklung werden Ihre Daten für die weitere Verwendung gesperrt, es sei denn, Sie haben gesondert in die weitere Verwendung eingewilligt. Nach Ablauf der steuer- und handelsrechtlichen Fristen werden diese Daten gelöscht, sofern Sie nicht ausdrücklich in eine weitere Nutzung eingewilligt haben. Nachstehende Regelungen informieren Sie insoweit über die Art, den Umfang und Zweck der Erhebung, die Nutzung und die Verarbeitung von personenbezogenen Daten.",
        privacyText6: "Sie haben die Möglichkeit uns bei Fragen, Wünschen und Anregungen zu kontaktieren. Dies können Sie u.a. per E-Mail tun. Soweit wir über unser Kontaktformular Eingaben abfragen, sind dies nur die zur Bearbeitung der Anfrage zwingend notwendigen Angaben. Diese Angaben dienen uns zur Konkretisierung Ihrer Anfrage und zur verbesserten Abwicklung Ihres Anliegens. In diesem Fall werden die von Ihnen gemachten Angaben zum Zwecke der Bearbeitung Ihrer Kontaktaufnahme gespeichert. Darüber hinaus erfolgt ein Abgleich der so erhobenen Daten mit Daten, die möglicherweise anderweitig von uns erhoben werden, wenn Sie uns vorher eine entsprechende Einwilligung erteilt haben, die Sie jederzeit mit Wirkung für die Zukunft widerrufen können. Für die Ausübung des Widerrufs wenden Sie sich bitte an die am Ende dieser Erklärung genannte Stelle.",
        privacyText7: "Ihre Daten werden Dienstleistungspartner weitergegeben, sofern diese in unserem Auftrag tätig sind und RICHLIST bei der Erbringung ihrer Dienste unterstützen. Eine Verarbeitung Ihrer personenbezogenen Daten durch beauftragte Dienstleister erfolgt im Rahmen der Auftragsverarbeitung gem. Art. 28 DSGVO. Die zuvor genannten Dienstleister erhalten lediglich Zugang zu solchen persönlichen Informationen, die zur Erfüllung der jeweiligen Tätigkeit erforderlich sind. Es ist diesen Dienstleistern untersagt, Ihre persönlichen Informationen weiterzugeben oder zu anderen Zwecken zu verwenden, insbesondere zu eigenen werblichen Zwecken. Soweit externe Dienstleister mit Ihren personenbezogenen Daten in Berührung kommen, haben wir durch rechtliche, technische und organisatorische Maßnahmen sowie durch regelmäßige Kontrollen sichergestellt, dass auch diese die geltenden Datenschutzvorschriften einhalten. Eine kommerzielle Weitergabe Ihrer personenbezogenen Daten an andere Unternehmen erfolgt nicht.",
        privacyText8: "Diese Webseite verwendet Google Analytics der Firma Google Ireland Limited (Gordon House, Barrow Street, Dublin 4, Irland). Gemäß der Vereinbarung zwischen Google und dem Hamburgischen Beauftragten für Datenschutz und Informationsfreiheit ist eine datenschutzkonforme und beanstandungsfreie Nutzung von Google Analytics unter bestimmten Bedingungen möglich. Insbesondere weisen wir darauf hin, dass auf dieser Webseite Google Analytics um die IP-Masking Funktion „_gat._anonymizeIp“ erweitert wurde, um eine anonymisierte Erfassung von IP-Adressen zu gewährleisten. Bitte beachten Sie auch die nachfolgenden Informationen zum Einsatz von Google Analytics: Google Analytics verwendet Cookies, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Webseite durch Sie ermöglichen. Die durch das Cookie erzeugten Informationen über Ihre Benutzung dieser Webseite werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Durch Aktivierung der IP-Anonymisierung auf dieser Webseite, wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers dieser Webseite wird Google diese Informationen benutzen, um Ihre Nutzung der Webseite auszuwerten, um Reports über die Webseitenaktivitäten zusammenzustellen und um weitere mit der Webseitennutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Webseitenbetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Webseite vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Webseite bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem Sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren. Sie können alternativ die Erfassung durch Google Analytics auch verhindern, indem Sie auf folgenden Link klicken. Es wird ein Opt-Out-Cookie gesetzt, das die zukünftige Erfassung Ihrer Daten beim Besuch dieser Website verhindert: Google Analytics deaktivieren. Das Opt-Out-Cookie gilt nur für diesen Browser und auch nur für diese Domain. Löschen Sie Ihre Cookies in diesem Browser, müssen Sie diesen Link erneut klicken. Nähere Informationen hierzu finden Sie unter https://www.google.de/intl/de/policies/ sowie in der Datenschutzerklärung von Google.",
        privacyText9: "",
        privacyText10: "",
        privacyText11: "",
        privacyText12: "",
        privacyText13: "",
        privacyText14: "",
        privacyText15: "",
        legalTeaser: "",
        legalHeader: "",
        legalTitle1: "",
        legalTitle2: "",
        legalTitle3: "",
        legalTitle4: "",
        legalTitle5: "",
        legalTitle6: "",
        legalTitle7: "",
  }
});